/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.airshipmanagergui;

/**
 *
 * @author Marek
 */
public class MyFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        updateContractFrame = new javax.swing.JFrame();
        updateContractLabel = new javax.swing.JLabel();
        contractDateLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        contractDateInput = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        contractLengthInput = new javax.swing.JTextPane();
        contractLengthLabel = new javax.swing.JLabel();
        contractClientLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        contractClientInput = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        contractDiscountInput = new javax.swing.JTextPane();
        contractDiscountLabel = new javax.swing.JLabel();
        contractAirshipLabel = new javax.swing.JLabel();
        contractAirshipInput = new javax.swing.JComboBox();
        contractPaymentInput = new javax.swing.JComboBox();
        contractPaymentLabel = new javax.swing.JLabel();
        updateContractSaveButton = new javax.swing.JButton();
        updateAirshipFrame = new javax.swing.JFrame();
        updateAirshipLabel = new javax.swing.JLabel();
        airshipNameLabel = new javax.swing.JLabel();
        airshipCapacityLabel = new javax.swing.JLabel();
        airshipPriceLabel = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        airshipNameInput = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        airshipPriceInput = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        airshipCapacityInput = new javax.swing.JTextPane();
        updateAirshipSaveButton = new javax.swing.JButton();
        AirshipManagerPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AirshipManagerPU").createEntityManager();
        airshipQuery = java.beans.Beans.isDesignTime() ? null : AirshipManagerPUEntityManager.createQuery("SELECT a FROM Airship a");
        airshipList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : airshipQuery.getResultList();
        contractQuery = java.beans.Beans.isDesignTime() ? null : AirshipManagerPUEntityManager.createQuery("SELECT c FROM Contract c");
        contractList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contractQuery.getResultList();
        jTabbedPane = new javax.swing.JTabbedPane();
        airshipTab = new javax.swing.JPanel();
        airshipManagerLabel = new javax.swing.JLabel();
        addAirshiptButton = new javax.swing.JButton();
        editAirshipButton = new javax.swing.JButton();
        removeAirshipButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        contractTab = new javax.swing.JPanel();
        contractManagerLabel = new javax.swing.JLabel();
        editContractButton = new javax.swing.JButton();
        addContractButton = new javax.swing.JButton();
        removeContractButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        updateContractFrame.setAlwaysOnTop(true);
        updateContractFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        updateContractLabel.setText("Add / Edit Contract");

        contractDateLabel.setText("Start Date");

        jScrollPane9.setViewportView(contractDateInput);

        jScrollPane11.setViewportView(contractLengthInput);

        contractLengthLabel.setText("Length");

        contractClientLabel.setText("Client Name");

        jScrollPane8.setViewportView(contractClientInput);

        jScrollPane12.setViewportView(contractDiscountInput);

        contractDiscountLabel.setText("Discount");

        contractAirshipLabel.setText("Airship");

        contractAirshipInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        contractPaymentInput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        contractPaymentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractPaymentInputActionPerformed(evt);
            }
        });

        contractPaymentLabel.setText("Payment method");

        updateContractSaveButton.setText("Save");

        javax.swing.GroupLayout updateContractFrameLayout = new javax.swing.GroupLayout(updateContractFrame.getContentPane());
        updateContractFrame.getContentPane().setLayout(updateContractFrameLayout);
        updateContractFrameLayout.setHorizontalGroup(
            updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateContractFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateContractFrameLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(updateContractSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateContractFrameLayout.createSequentialGroup()
                        .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contractAirshipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contractPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contractAirshipInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contractPaymentInput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateContractFrameLayout.createSequentialGroup()
                        .addComponent(contractDiscountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contractDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateContractFrameLayout.createSequentialGroup()
                        .addComponent(contractLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateContractFrameLayout.createSequentialGroup()
                        .addComponent(contractClientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateContractLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        updateContractFrameLayout.setVerticalGroup(
            updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateContractFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateContractLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractLengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(updateContractFrameLayout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractClientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contractDiscountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractAirshipInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractAirshipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateContractFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractPaymentInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(updateContractSaveButton)
                .addGap(31, 31, 31))
        );

        updateAirshipFrame.setAlwaysOnTop(true);

        updateAirshipLabel.setText("Add / Edit Airship");

        airshipNameLabel.setText("Name");

        airshipCapacityLabel.setText("Capacity");

        airshipPriceLabel.setText("Price");

        jScrollPane15.setViewportView(airshipNameInput);

        jScrollPane16.setViewportView(airshipPriceInput);

        jScrollPane17.setViewportView(airshipCapacityInput);

        updateAirshipSaveButton.setText("Save");
        updateAirshipSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateAirshipSaveButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout updateAirshipFrameLayout = new javax.swing.GroupLayout(updateAirshipFrame.getContentPane());
        updateAirshipFrame.getContentPane().setLayout(updateAirshipFrameLayout);
        updateAirshipFrameLayout.setHorizontalGroup(
            updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                .addGroup(updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                                .addComponent(airshipPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateAirshipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                                .addComponent(airshipNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                                .addComponent(airshipCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(updateAirshipSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        updateAirshipFrameLayout.setVerticalGroup(
            updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateAirshipFrameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(updateAirshipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(airshipNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(airshipCapacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateAirshipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(airshipPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateAirshipSaveButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        airshipManagerLabel.setText("Airship Manager dialog");

        addAirshiptButton.setText("Add Airship");
        addAirshiptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAirshiptButtonMouseClicked(evt);
            }
        });

        editAirshipButton.setText("Edit Airship");

        removeAirshipButton.setText("Remove Airship");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, airshipList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capacity}"));
        columnBinding.setColumnName("Capacity");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price} €"));
        columnBinding.setColumnName("Price");
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout airshipTabLayout = new javax.swing.GroupLayout(airshipTab);
        airshipTab.setLayout(airshipTabLayout);
        airshipTabLayout.setHorizontalGroup(
            airshipTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airshipTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(airshipTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airshipManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(airshipTabLayout.createSequentialGroup()
                        .addComponent(addAirshiptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAirshipButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeAirshipButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        airshipTabLayout.setVerticalGroup(
            airshipTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(airshipTabLayout.createSequentialGroup()
                .addComponent(airshipManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(airshipTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirshiptButton)
                    .addComponent(editAirshipButton)
                    .addComponent(removeAirshipButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Airship managment", airshipTab);

        contractManagerLabel.setText("Contract Manager dialog");

        editContractButton.setText("Edit Contract");

        addContractButton.setText("Add Contract");
        addContractButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addContractButtonMouseClicked(evt);
            }
        });

        removeContractButton.setText("Remove Contract");

        jTable2.getTableHeader().setReorderingAllowed(false);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, contractList, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${airshipid}"));
        columnBinding.setColumnName("Airship ID");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nameofclient}"));
        columnBinding.setColumnName("Client Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${startdate}"));
        columnBinding.setColumnName("Start Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${length}"));
        columnBinding.setColumnName("Length");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${discount}"));
        columnBinding.setColumnName("Discount");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${paymentmethod}"));
        columnBinding.setColumnName("Payment");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout contractTabLayout = new javax.swing.GroupLayout(contractTab);
        contractTab.setLayout(contractTabLayout);
        contractTabLayout.setHorizontalGroup(
            contractTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contractTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contractTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(contractTabLayout.createSequentialGroup()
                        .addGroup(contractTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contractManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contractTabLayout.createSequentialGroup()
                                .addComponent(addContractButton)
                                .addGap(18, 18, 18)
                                .addComponent(editContractButton)
                                .addGap(18, 18, 18)
                                .addComponent(removeContractButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        contractTabLayout.setVerticalGroup(
            contractTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractTabLayout.createSequentialGroup()
                .addComponent(contractManagerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contractTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addContractButton)
                    .addComponent(editContractButton)
                    .addComponent(removeContractButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Contract managment", contractTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addContractButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addContractButtonMouseClicked
       updateContractFrame.setVisible(true);
    }//GEN-LAST:event_addContractButtonMouseClicked

    private void addAirshiptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAirshiptButtonMouseClicked
        updateAirshipFrame.setVisible(true);
    }//GEN-LAST:event_addAirshiptButtonMouseClicked

    private void updateAirshipSaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateAirshipSaveButtonMouseClicked

    }//GEN-LAST:event_updateAirshipSaveButtonMouseClicked

    private void contractPaymentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractPaymentInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contractPaymentInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AirshipManagerPUEntityManager;
    private javax.swing.JButton addAirshiptButton;
    private javax.swing.JButton addContractButton;
    private javax.swing.JTextPane airshipCapacityInput;
    private javax.swing.JLabel airshipCapacityLabel;
    private java.util.List<cz.muni.fi.pv168.airshipmanagergui.Airship> airshipList;
    private javax.swing.JLabel airshipManagerLabel;
    private javax.swing.JTextPane airshipNameInput;
    private javax.swing.JLabel airshipNameLabel;
    private javax.swing.JTextPane airshipPriceInput;
    private javax.swing.JLabel airshipPriceLabel;
    private javax.persistence.Query airshipQuery;
    private javax.swing.JPanel airshipTab;
    private javax.swing.JComboBox contractAirshipInput;
    private javax.swing.JLabel contractAirshipLabel;
    private javax.swing.JTextPane contractClientInput;
    private javax.swing.JLabel contractClientLabel;
    private javax.swing.JTextPane contractDateInput;
    private javax.swing.JLabel contractDateLabel;
    private javax.swing.JTextPane contractDiscountInput;
    private javax.swing.JLabel contractDiscountLabel;
    private javax.swing.JTextPane contractLengthInput;
    private javax.swing.JLabel contractLengthLabel;
    private java.util.List<cz.muni.fi.pv168.airshipmanagergui.Contract> contractList;
    private javax.swing.JLabel contractManagerLabel;
    private javax.swing.JComboBox contractPaymentInput;
    private javax.swing.JLabel contractPaymentLabel;
    private javax.persistence.Query contractQuery;
    private javax.swing.JPanel contractTab;
    private javax.swing.JButton editAirshipButton;
    private javax.swing.JButton editContractButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton removeAirshipButton;
    private javax.swing.JButton removeContractButton;
    private javax.swing.JFrame updateAirshipFrame;
    private javax.swing.JLabel updateAirshipLabel;
    private javax.swing.JButton updateAirshipSaveButton;
    private javax.swing.JFrame updateContractFrame;
    private javax.swing.JLabel updateContractLabel;
    private javax.swing.JButton updateContractSaveButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
